name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine coverage[toml] flake8 isort

    - name: Run tests before release
      run: |
        make tests

    - name: Build package
      run: |
        make build

    - name: Check package
      run: |
        twine check dist/*

    # PyPI upload disabled - keeping distribution local only
    # - name: Publish to PyPI
    #   env:
    #     TWINE_USERNAME: __token__
    #     TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
    #   run: |
    #     twine upload dist/*

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes in this Release

          See [CHANGELOG.md](CHANGELOG.md) for detailed changes.

          ## Installation

          ```bash
          git clone https://github.com/cscortes/wipeit.git
          cd wipeit
          uv sync
          ```

          ## Usage

          ```bash
          sudo wipeit /dev/sdx
          ```
        draft: false
        prerelease: false
