name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine coverage[toml] flake8 isort

    - name: Run tests before release
      run: |
        make tests

    - name: Build package
      run: |
        make build

    - name: Check package
      run: |
        twine check dist/*

    # PyPI upload disabled - keeping distribution local only
    # - name: Publish to PyPI
    #   env:
    #     TWINE_USERNAME: __token__
    #     TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
    #   run: |
    #     twine upload dist/*

    - name: Create GitHub Release with Distribution Files
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.whl
          dist/*.tar.gz
        body: |
          ## Changes in this Release

          See [DOCS/CHANGES.md](https://github.com/cscortes/wipeit/blob/${{ github.ref_name }}/DOCS/CHANGES.md) for detailed changes.

          ## Installation Options

          ### Option 1: Install from Release Wheel (Recommended)
          Download the `.whl` file from the Assets section below, then:
          ```bash
          pip install wipeit-*.whl
          ```

          ### Option 2: Install from Source
          ```bash
          git clone https://github.com/cscortes/wipeit.git
          cd wipeit
          uv sync
          ```

          ## Usage

          ```bash
          # List devices
          sudo wipeit --list

          # Wipe a device (DESTRUCTIVE!)
          sudo wipeit /dev/sdx
          ```

          ## ⚠️ WARNING
          This tool **PERMANENTLY DESTROYS ALL DATA**. Use with extreme caution!
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
